### PR TITLE
Replace the screenshot in Readme.md with a gif 

### PR DESCRIPTION
**Pull request by t1war1**

### CODE REVIEW

**Comment by t1war1** [comment]
Fixes #20

**Comment by jajodiaraghav** [comment]
@thegauravtiwari Why are you using imgflip for this? All you have to do is record the application for a few seconds and save a GIF with some software. There are several options available. The put the gif in `assets` folder and move the `Audio` folder in it too

**Comment by jajodiaraghav** [comment]
Also, You have again made PR through master branch. This won't be merged

**Comment by t1war1** [comment]
Sorry! I made PR directly from github, forgot to make new branch before sending PR.

**Comment by jajodiaraghav** [comment]
> I made PR directly from github, forgot to make new branch before sending PR.

This doesn't seems right. Whenever you are working on a new issue/feature/bug, you have to create a new branch from your local master. You don't make a new branch from github.
Please go through the links properly.

**Pull request closed without merging**
